Removing the direct dependency on the attrs lib.
ApplauseOSS/kms-encryption-toolbox pull request #4
Opened 2018-01-22 12:47 UTC by rogoman

The direct dependency on the `attrs` lib was never used in the code. Removing, as it's blocking the lib users from upgrading their other libs.

This fixes https://github.com/ApplauseOSS/kms-encryption-toolbox/issues/3

2018-01-22 12:52 UTC, mieciu requested changes

2018-01-22 12:52 UTC, mieciu commented on setup.py
> +    version='0.0.15',
IMO we should bump to `0.1.0` in this case

2018-01-22 12:53 UTC, mieciu commented on test.py
> -import pdb; pdb.set_trace()
nice catch 😄

2018-01-22 12:53 UTC, fala approved these changes
LGTM after the version is bumped. Kudos for the other small fixes.

2018-01-22 12:53 UTC, mieciu approved these changes

2018-01-22 12:53 UTC, merged

2018-01-23 14:30 UTC, billcrook commented
👍